MyHoroscopes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('RajAstrologySigns/',include('MyZodiacSigns.urls')),
    path('',views.RajHoroscopicSignDetailView,name='Daily_Horoscopes'),

]
urlpatterns= urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns= urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

MyZodiacSigns/urls.py
from django.urls import path
from . import views
from django.contrib import admin
app_name='MyZodiacSigns'
urlpatterns=[
    path('',views.HomePageView,name="HomePage"),
    path('About/',views.AboutPageView,name="AboutPage"),
    path('DailyHoroscopes/',views.DailyHoroscopeDetailView,name="DailyHoroscopes"),
    path('TomorrowHoroscopes/',views.TomorrowHoroscopeDetailView,name='TomorrowHoroscopes'),
    path('WeeklyHoroscopes/',views.WeeklyHoroscopeDetailView,name='WeeklyHoroscopes'),
    path('MonthlyHoroscopes/',views.MonthlyHoroscopeDetailView,name="MonthlyHoroscopes"),
    path('YearlyHoroscopes/',views.YearlyHoroscopeDetailView,name='YearlyHoroscopes'),
    path('ZodiacSignFindings/',views.FindZodiacDetailView,name='ZodiacSignFindings'),
    path('LoveCompatibility/',views.ZodiacLoveCompatibilityDetailView,name="LoveCompatibility"),

    path('BirthdayDetails/General/',views.TodayBirthdateGeneralHoroscopeDetailView, name='TodayGeneralBirthday'),
    path('BirthdayDetails/GiftIdeas/',views.TodayBirthdateGiftDetailView, name='TodayBirthGiftDetails'),
    path('BirthdayDetails/PamperingIdeas/',views.TodayBirthdatePamperingDetailView, name='TodayBirthPamperingDetails'),
    path('BirthdayDetails/PartyIdeas/',views.TodayBirthdatePartyDetailView, name='TodayBirthPartyDetails'),
    path('BirthdayDetails/DestinationIdeas/',views.TodayBirthdateDestinationsDetailView, name='TodayBirthDestinationDetails'),
    path('BirthDatewise/GeneralOverallDetails/',views.DateWiseBirthDateGeneralOverallDetailView,name='DatewiseGeneralOverallDetails'),

    path('OverallHoroscopes/',views.OverallZodiacHoroscopesDetailView, name='OverallHoroscopeDetails'),
    path('OverallHoroscopes/AriesHoroscopes/',views.AriesHoroscopeDetailView, name='AriesHoroscopeDetails'),
    path('OverallHoroscopes/TaurusHoroscopes/',views.TaurusHoroscopeDetailView, name='TaurusHoroscopeDetails'),
    path('OverallHoroscopes/GeminiHoroscopes/',views.GeminiHoroscopeDetailView, name='GeminiHoroscopeDetails'),
    path('OverallHoroscopes/CancerHoroscopes/',views.CancerHoroscopeDetailView, name='CancerHoroscopeDetails'),
    path('OverallHoroscopes/LeoHoroscopes/',views.LeoHoroscopeDetailView,name="LeoHoroscopeDetails"),
    path('OverallHoroscopes/VirgoHoroscopes/',views.VirgoHoroscopeDetailView,name="VirgoHoroscopeDetails"),
    path('OverallHoroscopes/LibraHoroscopes/',views.LibraHoroscopeDetailView,name="LibraHoroscopeDetails"),
    path('OverallHoroscopes/ScorpioHoroscopes/',views.ScorpioHoroscopeDetailView,name="ScorpioHoroscopeDetails"),
    path('OverallHoroscopes/SagittariusHoroscopes/',views.SagittariusHoroscopeDetailView,name="SagittariusHoroscopeDetails"),
    path('OverallHoroscopes/CapricornHoroscopes/',views.CapricornHoroscopeDetailView,name="CapricornHoroscopeDetails"),
    path('OverallHoroscopes/AquariusHoroscopes/',views.AquariusHoroscopeDetailView,name="AquariusHoroscopeDetails"),
    path('OverallHoroscopes/PiscesHoroscopes/',views.PiscesHoroscopeDetailView,name="PiscesHoroscopeDetails"),
    
    path('AriesBasicZodiacDetails/',views.AriesBasicZodiacDetailView,name='AriesBasicZodiacDetails'),
    path('TaurusBasicZodiacDetails/',views.TaurusBasicZodiacDetailView,name='TaurusBasicZodiacDetails'),
    path('GeminiBasicZodiacDetails/',views.GeminiBasicZodiacDetailView,name='GeminiBasicZodiacDetails'),
    path('CancerBasicZodiacDetails/',views.CancerBasicZodiacDetailView,name='CancerBasicZodiacDetails'),
    path('LeoBasicZodiacDetails/',views.LeoBasicZodiacDetailView,name='LeoBasicZodiacDetails'),
    path('VirgoBasicZodiacDetails/',views.VirgoBasicZodiacDetailView,name='VirgoBasicZodiacDetails'),
    path('LibraBasicZodiacDetails/',views.LibraBasicZodiacDetailView,name='LibraBasicZodiacDetails'),
    path('ScorpioBasicZodiacDetails/',views.ScorpioBasicZodiacDetailView,name='ScorpioBasicZodiacDetails'),
    path('SagittariusBasicZodiacDetails/',views.SagittariusBasicZodiacDetailView,name='SagittariusBasicZodiacDetails'),
    path('CapricornBasicZodiacDetails/',views.CapricornBasicZodiacDetailView,name='CapricornBasicZodiacDetails'),
    path('AquariusBasicZodiacDetails/',views.AquariusBasicZodiacDetailView,name='AquariusBasicZodiacDetails'),
    path('PiscesBasicZodiacDetails/',views.PiscesBasicZodiacDetailView,name='PiscesBasicZodiacDetails'),
    
    path('ZodiacOverallview/',views.OverallZodiacOverviewDetailView,name='OverallZodiacOverviewDetails'),
    path('ZodiacOverallview/AriesZodiac/',views.AriesZodiacOverviewDetailView,name='AriesZodiacOverview'),
    path('ZodiacOverallview/TaurusZodiac/',views.TaurusZodiacOverviewDetailView,name='TaurusZodiacOverview'),
    path('ZodiacOverallview/GeminiZodiac/',views.GeminiZodiacOverviewDetailView,name='GeminiZodiacOverview'),
    path('ZodiacOverallview/CancerZodiac/',views.CancerZodiacOverviewDetailView,name='CancerZodiacOverview'),
    path('ZodiacOverallview/LeoZodiac/',views.LeoZodiacOverviewDetailView,name='LeoZodiacOverview'),
    path('ZodiacOverallview/VirgoZodiac/',views.VirgoZodiacOverviewDetailView,name='VirgoZodiacOverview'),
    path('ZodiacOverallview/LibraZodiac/',views.LibraZodiacOverviewDetailView,name='LibraZodiacOverview'),
    path('ZodiacOverallview/ScorpioZodiac/',views.ScorpioZodiacOverviewDetailView,name='ScorpioZodiacOverview'),
    path('ZodiacOverallview/SagittariusZodiac/',views.SagittariusZodiacOverviewDetailView,name='SagittariusZodiacOverview'),
    path('ZodiacOverallview/CapricornZodiac/',views.CapricornZodiacOverviewDetailView,name='CapricornZodiacOverview'),
    path('ZodiacOverallview/AquariusZodiac/',views.AquariusZodiacOverviewDetailView,name='AquariusZodiacOverview'),
    path('ZodiacOverallview/PiscesZodiac/',views.PiscesZodiacOverviewDetailView,name='PiscesZodiacOverview'),

    path('MyZodiacCareers/',views.ZodiacCareerDetailView,name='MyZodiacCareerDetails'),
    path('MyZodiacCareers/AriesCareers/',views.AriesZodiacCareerDetailView,name="AriesZodiacCareerDetails"),
    path('MyZodiacCareers/TaurusCareers/',views.TaurusZodiacCareerDetailView,name="TaurusZodiacCareerDetails"),
    path('MyZodiacCareers/GeminiCareers/',views.GeminiZodiacCareerDetailView,name="GeminiZodiacCareerDetails"),
    path('MyZodiacCareers/CancerCareers/',views.CancerZodiacCareerDetailView,name="CancerZodiacCareerDetails"),
    path('MyZodiacCareers/LeoCareers/',views.LeoZodiacCareerDetailView,name="LeoZodiacCareerDetails"),
    path('MyZodiacCareers/VirgoCareers/',views.VirgoZodiacCareerDetailView,name="VirgoZodiacCareerDetails"),
    path('MyZodiacCareers/LibraCareers/',views.LibraZodiacCareerDetailView,name="LibraZodiacCareerDetails"),
    path('MyZodiacCareers/ScorpioCareers/',views.ScorpioZodiacCareerDetailView,name="ScorpioZodiacCareerDetails"),
    path('MyZodiacCareers/SagittariusCareers/',views.SagittariusZodiacCareerDetailView,name="SagittariusZodiacCareerDetails"),
    path('MyZodiacCareers/CapricornCareers/',views.CapricornZodiacCareerDetailView,name="CapricornZodiacCareerDetails"),
    path('MyZodiacCareers/AquariusCareers/',views.AquariusZodiacCareerDetailView,name="AquariusZodiacCareerDetails"),
    path('MyZodiacCareers/PiscesCareers/',views.PiscesZodiacCareerDetailView,name="PiscesZodiacCareerDetails"),
    
    path('MyZodiacHealth/',views.ZodiacHealthDetailView,name='MyZodiacHealthDetails'),
    path('MyZodiacHealth/AriesHealth/',views.AriesZodiacHealthDetailView,name="AriesZodiacHealthDetails"),
    path('MyZodiacHealth/TaurusHealth/',views.TaurusZodiacHealthDetailView,name="TaurusZodiacHealthDetails"),
    path('MyZodiacHealth/GeminiHealth/',views.GeminiZodiacHealthDetailView,name="GeminiZodiacHealthDetails"),
    path('MyZodiacHealth/CancerHealth/',views.CancerZodiacHealthDetailView,name="CancerZodiacHealthDetails"),
    path('MyZodiacHealth/LeoHealth/',views.LeoZodiacHealthDetailView,name="LeoZodiacHealthDetails"),
    path('MyZodiacHealth/VirgoHealth/',views.VirgoZodiacHealthDetailView,name="VirgoZodiacHealthDetails"),
    path('MyZodiacHealth/LibraHealth/',views.LibraZodiacHealthDetailView,name="LibraZodiacHealthDetails"),
    path('MyZodiacHealth/ScorpioHealth/',views.ScorpioZodiacHealthDetailView,name="ScorpioZodiacHealthDetails"),
    path('MyZodiacHealth/SagittariusHealth/',views.SagittariusZodiacHealthDetailView,name="SagittariusZodiacHealthDetails"),
    path('MyZodiacHealth/CapricornHealth/',views.CapricornZodiacHealthDetailView,name="CapricornZodiacHealthDetails"),
    path('MyZodiacHealth/AquariusHealth/',views.AquariusZodiacHealthDetailView,name="AquariusZodiacHealthDetails"),
    path('MyZodiacHealth/PiscesHealth/',views.PiscesZodiacHealthDetailView,name="PiscesZodiacHealthDetails"),

    path('MyZodiacLove/',views.ZodiacLoveDetailView,name='MyZodiacLoveDetails'),
    path('MyZodiacLove/AriesLove/',views.AriesZodiacLoveDetailView,name='AriesZodiacLoveDetails'),
    path('MyZodiacLove/TaurusLove/',views.TaurusZodiacLoveDetailView,name='TaurusZodiacLoveDetails'),
    path('MyZodiacLove/GeminiLove/',views.GeminiZodiacLoveDetailView,name='GeminiZodiacLoveDetails'),
    path('MyZodiacLove/CancerLove/',views.CancerZodiacLoveDetailView,name='CancerZodiacLoveDetails'),
    path('MyZodiacLove/LeoLove/',views.LeoZodiacLoveDetailView,name='LeoZodiacLoveDetails'),
    path('MyZodiacLove/VirgoLove/',views.VirgoZodiacLoveDetailView,name='VirgoZodiacLoveDetails'),
    path('MyZodiacLove/LibraLove/',views.LibraZodiacLoveDetailView,name='LibraZodiacLoveDetails'),
    path('MyZodiacLove/ScorpioLove/',views.ScorpioZodiacLoveDetailView,name='ScorpioZodiacLoveDetails'),
    path('MyZodiacLove/SagittariusLove/',views.SagittariusZodiacLoveDetailView,name='SagittariusZodiacLoveDetails'),
    path('MyZodiacLove/CapricornLove/',views.CapricornZodiacLoveDetailView,name='CapricornZodiacLoveDetails'),
    path('MyZodiacLove/AquariusLove/',views.AquariusZodiacLoveDetailView,name='AquariusZodiacLoveDetails'),
    path('MyZodiacLove/PiscesLove/',views.PiscesZodiacLoveDetailView,name='PiscesZodiacLoveDetails'),
    

MyZodiacSigns/models.py
from django.db import models

MyZodiacSigns/forms.py
from numbers import Number
from django import forms
Zodiacs=(("Aries","Aries"),("Taurus","Taurus"),("Gemini","Gemini"),("Cancer","Cancer"),("Leo","Leo"),("Virgo","Virgo"),
("Libra","Libra"),("Scorpio","Scorpio"),("Sagittarius","Sagittarius"),("Capricorn","Capricorn"),("Aquarius","Aquarius"),("Pisces","Pisces"))
Months=(("January","January"),("February","February"),("March","March"),("April","April"),("May","May"),("June","June"),
("July","July"),("August","August"),("September","September"),("October","October"),("November","Novemeber"),("December","December"))
# creating a form
class ZodiacFindingDetailForm(forms.Form):
	person_name = forms.CharField(label='What is your name:',max_length=50,help_text="Please enter your full name")
	Age = forms.IntegerField(max_value=100,label="Enter your Age:",help_text="Please check enter your age and check it should be below 100 in general.")
	birth_date = forms.DateField(label='What is your birth date:', help_text="Please enter your correct birthdate",widget=forms.NumberInput(attrs={'type':'date'}))

class ZodiacLoveCompatibilityForm(forms.Form):
	First_Zodiac_Sign = forms.ChoiceField(widget=forms.Select, choices=Zodiacs,label="Enter your zodiac sign")
	Second_Zodiac_Sign = forms.ChoiceField(widget=forms.Select, choices=Zodiacs,label="Enter your Partner zodiac sign")

class BirthDateDetailForm(forms.Form):
	person_name = forms.CharField(label='What is your name?',max_length=50,help_text='Please enter your name')
	Birth_Date = forms.ChoiceField(widget=forms.Select,choices=[(x,x) for x in range(1,32)],help_text="Enter your birthday Date",label="Enter your Birthday Date:")
	Birth_Month = forms.ChoiceField(widget=forms.Select,choices= Months,help_text="Enter your birthday Date",label="Enter your Birthday Month:")

MyZodiacSigns/templates/MyZodiacSigns/Zodiac_Signs/Gemini_Zodiac/Money/MoneyDetails.html
{% extends 'MyZodiacSigns/Navbar.html' %}
{% load static %}

{% block title %}Gemini Money Details{% endblock title %}
{% block content %}
<div class="Image-container">
    <img class='image-carousel-sty' src="/media/Zodiac_carousels/Gemini_Zodiac.png" />
    <div class="image-text-block">
        <p class='block-text'><a href="#ZodiacMoneyContent" class='block-asty btn btn-primary'>
                <i class="fa-solid fa-chart-simple"></i>&nbsp;Gemini Money Details</i></a></p>
    </div>
</div>
<div class="Total-content" id="ZodiacMoneyContent">
    <div class="container">
        <!-- NAV PILLS-->
        <ul class="nav nav-pills nav-fill ">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="pill" href="#WeeklyMoneyDetails"><span><img class="img-tab-sty" src="/media/Horoscope_Types/Weekly_Symbol.png" /><span
                    class="info-sty d-none d-md-inline-block">WEEKLY</span></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'MyZodiacSigns:GeminiZodiacOverview' %}"><span><img class="img-tab-sty" src="/media/Horoscope_Types/Yearly_Horoscopes.png" /><span
                    class="info-sty d-none d-md-inline-block">{{GeminiMoneyDetails.Year}}</span></span></a>
            </li>
        </ul>
        <div class="tab-content">
            <div id="WeeklyMoneyDetails" class='container tab-pane active'>
                <h4 class="Detail-Caption-Sty">Gemini Weekly Money Details</h4>
                <div class='Content-Description-Sty'>
                    <p><span class="strong-text">{{GeminiMoneyDetails.start_week_date}}&nbsp;-&nbsp;{{GeminiMoneyDetails.end_week_date}}</span>&nbsp;-&nbsp;<span class='desc-sty'>{{GeminiMoneyDetails.Weekly_Description}}</span></p>
                </div>
                <div class="LinkContainerDetailSty">
                    <h4 class="LinkCaptionSty">More details about Gemini Zodiac Sign</h4>
                    <span class="LinkDetails"><a class="link-item" href="{% url 'MyZodiacSigns:GeminiZodiacOverview' %}">Gemini Overview Details</a><a class="link-item"
                            href="{% url 'MyZodiacSigns:GeminiBasicZodiacDetails' %}">Gemini Basic Details</a><a class="link-item" href="{% url 'MyZodiacSigns:GeminiHoroscopeDetails' %}">Gemini Horoscope Details</a>
                            <a class="link-item" href="{% url 'MyZodiacSigns:GeminiZodiacCareerDetails' %}">Gemini Career Details</a><a class="link-item" href="{% url 'MyZodiacSigns:GeminiZodiacHealthDetails' %}">Gemini Health Details</a>
                            <a class="link-item" href="{% url 'MyZodiacSigns:GeminiZodiacLoveDetails' %}">Gemini Love Details</a><a class="link-item" href="{% url 'MyZodiacSigns:GeminiZodiacMoneyDetail' %}">Gemini Money Details</a>
                            <a class="link-item" href="{% url 'MyZodiacSigns:GeminiZodiacRetailDetails' %}">Gemini Retail Details</a></span>
                    <h4 class="LinkCaptionSty">More details about All Zodiac Signs</h4>
                    <span class="LinkDetails"><a class="link-item" href="{% url 'MyZodiacSigns:OverallZodiacOverviewDetails' %}">Overall view Details</a>
                        <a class="link-item" href="{% url 'MyZodiacSigns:HomePage' %}">Overall Horoscope Details</a><a class="link-item" href="{% url 'MyZodiacSigns:MyZodiacCareerDetails' %}">Overall Career
                            Details</a><a class="link-item" href="{% url 'MyZodiacSigns:MyZodiacHealthDetails' %}">Overall Health Details</a><a class="link-item" href="{% url 'MyZodiacSigns:MyZodiacLoveDetails' %}">Overall Love Details</a>
                            <a class="link-item" href="{% url 'MyZodiacSigns:MyZodiacMoneyDetails' %}">Overall Money Details</a><a class="link-item" href="{% url 'MyZodiacSigns:MyZodiacRetailDetails' %}">Overall Retail Details</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}